### ISSUE TITLE
Can't import your repo

### ISSUE THREAD

**Issue by runpengchensc** [mreinstein/node-gearman#20]
I try to use your repo. I install the package by `npm install --save gearman`. However, it doesn't work. I go to your repo and do `npm install`. But it seems like it can't pass the test. It is Error.
`> gearman@2.0.2 prepublish /Users/gearman-admin/node_modules/gearman
> npm test

> gearman@2.0.2 test /Users/gearman-admin/node_modules/gearman
> nodeunit tests

/Users/gearman-admin/node_modules/gearman/index.js:32
module.exports = function gearman(host='127.0.0.1', port=4730, options={}) {
                                      ^
`

Thanks. I am newbie.

**Comment by runpengchensc** [comment]
Once I delete all default, it works.

**Comment by mreinstein** [comment]
what version of node are you running? gearman 2.x is node 6+

**Comment by runpengchensc** [comment]
@mreinstein Thank you. That make sense! I am using node 4.5
